version: "3"

services:
    app:
        restart: always
        build: ./
        # command: npm run serve:api
        # add localhost to ports
        ports:
            - "7999:7999"
        links:
            - mongo
    mongo:
        image: mongo
        # volumes:
        #     - ./data:/data/db
        ports:
            - "27017:27017"
    test:
        build: ./
        environment:
            - CI=true
        command: npm run test
