<template>
  <div class="about-container">
    <div id="intro" class="about-content-section">
      <div class="quote">
        <em class="quote-intro"
          >There is a celebrated theorem which has been proven by Kenneth
          Arrow:</em
        >
        <cite
          >"No fair voting system exists if there are three or more
          parties..."</cite
        >
        <feather
          id="bouncing-arrow"
          type="chevron-down"
          @click="scrollMeTo('about-main')"
        />
      </div>
    </div>
    <section id="about-main" ref="about-main" class="about-content-section">
      <h1 class="about-head">The instant runoff voting tool</h1>
      <em>
        How do democratic polls work? The winning candidate is simply the one
        that gets the most votes... Right? You find a winner through raising
        hands and choosing the option that got the most votes. This voting
        system is called "first past the post".
      </em>
      <h3>Here's why this isn't very democratic:</h3>
      <ul class="about-list">
        <li>
          ... The winner takes it all. If someone voted for a minority (even if
          this minority is relatively popular), their vote is lost.
        </li>
        <li>
          ... Tactical voting might occur when voters are prone to vote in a way
          that doesn't really reflect their personal preferences.
        </li>
        <li>
          ... If the election isn't secret, voters are influenced by group
          dynamics (e.g. when they are worried about what influencers or opinion
          leaders might think.)
        </li>
      </ul>

      <p>
        Voting the instant runoff way, or the alternative way, has a number of
        advantages over first past the post. It ensures that the winning
        candidate receives the support of the majority of voters.
      </p>
      <router-link to="Polls">
        <TextButton text="Try it out" icon="link" background-color="#0bb3a2" />
      </router-link>
    </section>

    <section class="about-content-section">
      <h2 class="about-head">How does the instant runoff vote work?</h2>
      <p>
        In this tool, voting is done with preference ballots, and a ranking is
        generated by every voter. As soon as we want to see results, we count up
        the voters' first choices. Then the choice with the least first-place
        votes is eliminated from the election, and any votes for that candidate
        are redistributed to the voters’ next choice. This continues until a
        choice has a majority (over 50% of all votes).
      </p>
      <em
        >Sounds complicated? Here's a video that explains this step by step:</em
      >
      <iframe
        src="https://www.youtube.com/embed/wA3_t-08Vr0"
        frameborder="0"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen
      />
    </section>

    <section class="about-content-section">
      <h2 class="about-head">If done correctly, the alternative vote...</h2>
      <ul class="about-list">
        <li>... Minimizes negative campaigning</li>
        <li>
          ... Provides more diverse choice options („I prefer A, but B is also
          OK“)
        </li>
        <li>
          ... Reduces (but does not eliminate!) the numbers of "wasted" votes
        </li>
        <li>
          ... Prevents second elections (e.g. top two). As the name "instant
          runoff" already states: in the standard case, runoff votes can be
          avoided.
        </li>
      </ul>
      <router-link to="Polls">
        <TextButton
          text="Go see the polls"
          icon="link"
          background-color="#0bb3a2"
        />
      </router-link>
    </section>

    <section class="about-content-section">
      <h2 class="about-head">Things to check up front</h2>
      <ul class="about-list">
        <li>
          <em class="questions"
            >Do you have more than three candidates/options?</em
          >
        </li>
        <p>
          The instant runoff vote is a bit pointless unless you have at least
          three candidates/options.
        </p>
        <li>
          <em class="questions">Do you have more than 9 voters?</em>
        </li>
        <p>Unless you have at least 9 voters, your results might be weird.</p>

        <li>
          <em class="questions">Are you looking for one winner?</em>
        </li>
        <p>
          Voting the instant runoff way is the “fairer” winner-take-all
          election. It is appropriate when no other alternatives are possible,
          e.g. if you need to find one single winner. In most cases, it also
          provides information about the runner-ups. But if you need a
          proportional representation (as in a parliament), it's not what you
          should go for.
        </p>
        <li>
          <em class="questions">What are you trying to find out?</em>
        </li>
        <p>
          Are you making this poll to find out tendencies or is this the real
          thing? In this tool, every opinion counts the same. But are there any
          follow-up decisions? Who has the final word? Make sure you know what
          to do with the results up front in order to avoid misunderstandings.
        </p>
      </ul>
      <router-link to="NewPoll">
        <TextButton
          text="Create a new Poll"
          icon="plus"
          background-color="#0bb3a2"
        />
      </router-link>
    </section>
  </div>
</template>

<script>
import TextButton from "./TextButton";
export default {
  name: "About",
  components: {
    TextButton
  },
  methods: {
    scrollMeTo(refName) {
      const element = this.$refs[refName];
      const top = element.offsetTop;
      window.scrollTo({ left: 0, top: top - 60, behavior: "smooth" });
    }
  }
};
</script>

<style lang="scss" scoped>
@keyframes bounce {
  0%,
  20%,
  50%,
  80%,
  100% {
    transform: translateY(0);
  }
  40% {
    transform: translateY(-16px);
  }
  60% {
    transform: translateY(-16px);
  }
}

#bouncing-arrow {
  animation: bounce 2s infinite;
  cursor: pointer;
  height: 30px;
  padding: 5vw 0 5vw 0;
}

#intro {
  display: flex;
  flex-wrap: wrap;
  height: 100vh;
  align-items: center;
  background-color: #202181;
}
.about-container {
  margin: auto;
  width: 100vw;
  p,
  ul,
  em {
    display: block;
    max-width: 75%;
    margin-bottom: 8px;
    @media (max-width: 750px) {
      max-width: 100%;
    }
  }
}

.about-content-section {
  padding-left: 15vw;
  padding-right: 15vw;
  margin-left: auto;
  margin-right: auto;
  @media (max-width: 750px) {
    padding-left: 5vw;
    padding-right: 5vw;
  }
}

section {
  margin: 100px 0 100px 0;
}

.about-h {
  font-size: 3rem;
  display: block;
  margin: 3rem 0 1.3rem 0;
  @media (max-width: 750px) {
    font-size: 2.5em;
  }
}
.quote {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 32px auto 64px;
  text-align: center;
  max-width: 70%;
  cite {
    font-size: 4rem;
    font-family: "plex-mono-italic";
    line-height: 105%;
    color: #84e6dc;
    @media (max-width: 750px) {
      font-size: 2.5rem;
    }
  }
}

em {
  font-size: 1.3em;
  color: white;
  margin: 24px 0 0 0;
  font-family: "plex-medium";
  font-style: normal;
}

li {
  font-size: 1.3rem;
  .questions {
    font-size: 1rem;
    margin-bottom: 0;
  }
}

iframe {
  min-width: 60vw;
  min-height: 45vw;
  max-width: 80vw;
  max-height: 60vw;
  // @media (max-width: 560px) {
  //   min-width: 300px;
  // }
}

.about-list {
  flex-direction: column;
}
</style>
